<?php
/**
 * @copyright Copyright (c) 2018 www.innovadeltech.com
 */
?>
<?php
$enableModule = $block->_scopeConfig->getValue('socialshare/general/enabled', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$enableGooglePlus = $block->_scopeConfig->getValue('socialshare/googleplus/enable_google_plus', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
?>

<div class="share">
    <?php
    if ($enableModule == 1) {
        if ($enableGooglePlus == 1) {
            ?>
            <div class="google_button social-button">
                <script src="https://apis.google.com/js/platform.js" async defer></script>
                <g:plus action="share"></g:plus> </div>   <?php
        }
    }
    ?>  
</div>